-- JOB_INFO 테이블 생성
-- SALARY는 $(달러)기준!
CREATE TABLE JOB_INFO(
    JOB_ID VARCHAR2(10), -- 직업 아이디
    MIN_SALARY NUMBER, -- 최저 급여
    MAX_SALARY NUMBER -- 최고 급여
);

INSERT INTO JOB_INFO VALUES('AD_PRES', 20000, 40000); 
INSERT INTO JOB_INFO VALUES('AD_VP', 15000, 30000); 
INSERT INTO JOB_INFO VALUES('AD_ASST', 3000, 6000); 
INSERT INTO JOB_INFO VALUES('FI_MGR', 8000, 16000); 
INSERT INTO JOB_INFO VALUES('FI_ACCOUNT', 4000, 9000); 
INSERT INTO JOB_INFO VALUES('AC_MGR', 8000, 16000); 
INSERT INTO JOB_INFO VALUES('AC_ACCOUNT', 4000, 9000); 

COMMIT;
SELECT * FROM JOB_INFO;

-- 최저급여의 평균을 구하시오 
SELECT ROUND(AVG(MIN_SALARY), -1) AS 최저급여_평균,
    AVG(MAX_SALARY) 최고급여_평균
FROM JOB_INFO;
  
-- 최저 급여가 5000달러 이상인 정보를 검색한 뷰 생성
CREATE VIEW V_JOB_INFO
AS SELECT * 
FROM JOB_INFO
WHERE MIN_SALARY >= 5000;

-- 최고 급여와 최저 급여의 차가 10000달러 이상인 직업아이디 수를 구하시오
SELECT JOB_ID
FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY >= 10000;

SELECT * FROM V_JOB_INFO;
DROP VIEW V_JOB_INFO;
DROP TABLE JOB_INFO;

-- 직업 ID의 이름이 FI로 시작하는 자료를 검색하시오 
SELECT * FROM V_JOB_INFO 
WHERE JOB_ID LIKE 'FI%';

-- MAX_SALARY가 최고인 직업아이디를 검색하시오
SELECT MAX(MAX_SALARY) AS 최고급여 FROM V_JOB_INFO; 

DROP VIEW V_JOB_INFO;
