-- 행 순서 관련 함수
-- lead() : 하위 행의 값을 상위 행에 출력 (=위로 올리기)
-- lag() : 상위 행의 값을 하위 행에 출력  (=아래로 내리기)
CREATE TABLE EMP_INFO(
    EMP_NO VARCHAR2(3), -- 사원번호
    NAME VARCHAR2(20),  -- 사원이름
    SALARY NUMBER   -- 급여(달러기준)
);

INSERT INTO EMP_INFO VALUES('100', 'Lia', 24000);
INSERT INTO EMP_INFO VALUES('101', 'jihun', 7000);
INSERT INTO EMP_INFO VALUES('102', 'yeeun', 8000);
INSERT INTO EMP_INFO VALUES('108', 'son', 12000);
INSERT INTO EMP_INFO VALUES('109', 'kang', 6000);
INSERT INTO EMP_INFO VALUES('110', 'roha', 15000);
INSERT INTO EMP_INFO VALUES('111', 'minjae', 21000);
INSERT INTO EMP_INFO VALUES('112', 'kangin', 16000);
INSERT INTO EMP_INFO VALUES('113', 'woo', 9000);
INSERT INTO EMP_INFO VALUES('119', 'kim', 13000);

SELECT * FROM EMP_INFO;

-- SAL2 : 3행 위로 출력, SAL3 : NULL인 경우 0으로 표기 >> LEAD() 
-- 상위 3개 값 사라짐
SELECT EMP_NO, NAME, SALARY, 
LEAD(SALARY, 3)OVER(ORDER BY SALARY DESC)SAL2,
LEAD(SALARY, 3, 0)OVER(ORDER BY SALARY DESC) SAL3
FROM EMP_INFO;

-- SAL2 : 3행 아래로 출력, SAL3 : NULL인 경우 0으로 표기 >> LAG()
-- 하위 3개 값 사라짐
SELECT EMP_NO, NAME, SALARY, 
LAG(SALARY, 3)OVER(ORDER BY SALARY DESC)SAL2,
LAG(SALARY, 3, 0)OVER(ORDER BY SALARY DESC) SAL3
FROM EMP_INFO;




